# Libraries

In [1]:
# Import Packages
import os
import numpy as np
import polars as pl
import pyarrow.dataset as pads
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# import sklearn.metrics

# Establish OF Pos

In [2]:
# Read in what pos to process
of_pos_file = open("of_pos.txt", "r")
of_pos = int(of_pos_file.read())
of_pos_file.close()

# Read in Data

In [ ]:
####################################################
### Code Taken from SMT_Data_Starter
####################################################

# For the data_path argument, include the full file path to the folder that holds the data!    
def readDataSubset(table_type, data_path=):
    '''
    Takes a the set of tables from Data set and
    transforms into panda data frame for manipulation
    
    Input:
    -     table_type   = Set of tables of interest from Data set [str]
    -     data_path    = File Path which data is located in Local device, change as necessary[str]
    
    '''
    if table_type not in ['ball-positions', 'ball-events', 'player-positions', 'lineups', 'game-info']:
        print("Invalid data subset name. Please try again with a valid data subset.")
        return -1

    if table_type == 'lineups' or table_type == 'game-info':
        return pads.dataset(source = os.path.join(os.path.dirname(__name__), data_path, table_type + '.csv'), format = 'csv')
    else:
        return pads.dataset(source = os.path.join(os.path.dirname(__name__), data_path, table_type), format = 'csv', partitioning = ['home_team', 'away_team', 'year', 'day'])

In [4]:
####################################################
### Code Taken from SMT_Data_Starter
####################################################

# Read in the Ball Events Data
ball_events_subset = readDataSubset('ball-events')
ball_events = ball_events_subset.to_table().to_pandas()
ball_events_df = pl.from_pandas(ball_events)

# Read in the Ball Pos Data
ball_pos_subset = readDataSubset('ball-positions')
ball_pos = ball_pos_subset.to_table().to_pandas()
ball_pos_df = pl.from_pandas(ball_pos)

# Read in the Player Pos Data for chosen OF pos
player_pos_subset = readDataSubset('player-positions')
player_pos = player_pos_subset.to_table(filter = (pads.field("player_id") == of_pos)).to_pandas()
player_pos_df = pl.from_pandas(player_pos)

# Find Timestamps for Contact and Next Event

In [34]:
# Find the timestamp for contact of all hits that either bounce off the ground or are caught by the targeted fielder
bbip_hit_df = ball_events_df \
                               .filter(
                                   (pl.col("player_id") == 10) &
                                   (pl.col("ball_eventcode") == 4) &
                                   (pl.col("player_id").shift(-1).is_in([of_pos, 255])) &
                                   (pl.col("ball_eventcode").shift(-1).is_in([2, 16]))
                                  ) \
                                .with_columns(
                                    pl.col("timestamp").alias("hit_timestamp")
                                ) \
                                .select(
                                    ["game_string", "play_per_game", "hit_timestamp"]
                                ) \
                                .drop_nulls(
                                ) \
                                .sort(
                                    ["game_string", "play_per_game"]
                                     )

# Find the timestamp after contact of all hits that either bounce off the ground or are caught by the targeted fielder to give us the next event
bbip_next_event_df = ball_events_df \
                               .filter(
                                   (pl.col("player_id").shift(1) == 10) &
                                   (pl.col("ball_eventcode").shift(1) == 4) &
                                   (pl.col("player_id").is_in([of_pos, 255])) &
                                   (pl.col("ball_eventcode").is_in([2, 16]))
                                  ) \
                                .with_columns(
                                    pl.col("timestamp").alias("next_event_timestamp")
                                ) \
                                .select(
                                      ["game_string", "play_per_game", "player_id", "ball_eventcode", "next_event_timestamp"]
                                )\
                                .drop_nulls(
                                ) \
                                .sort(
                                    ["game_string", "play_per_game"]
                                )

shape: (8_344, 5)
┌─────────────────┬───────────────┬───────────┬────────────────┬──────────────────────┐
│ game_string     ┆ play_per_game ┆ player_id ┆ ball_eventcode ┆ next_event_timestamp │
│ ---             ┆ ---           ┆ ---       ┆ ---            ┆ ---                  │
│ str             ┆ f64           ┆ i64       ┆ i64            ┆ f64                  │
╞═════════════════╪═══════════════╪═══════════╪════════════════╪══════════════════════╡
│ y1_d061_VKA_PHD ┆ 2.0           ┆ 255       ┆ 16             ┆ 76464.0              │
│ y1_d061_VKA_PHD ┆ 3.0           ┆ 255       ┆ 16             ┆ 110064.0             │
│ y1_d061_VKA_PHD ┆ 11.0          ┆ 255       ┆ 16             ┆ 396064.0             │
│ y1_d061_VKA_PHD ┆ 22.0          ┆ 255       ┆ 16             ┆ 720514.0             │
│ y1_d061_VKA_PHD ┆ 25.0          ┆ 255       ┆ 16             ┆ 913914.0             │
│ …               ┆ …             ┆ …         ┆ …              ┆ …                    │
│ y1_d217_VAS_ARN ┆ 307.0         ┆ 255       ┆ 16             ┆ 9.857836e6           │
│ y1_d217_VAS_ARN ┆ 316.0         ┆ 9         ┆ 2              ┆ 1.0070386e7          │
│ y1_d217_VAS_ARN ┆ 321.0         ┆ 255       ┆ 16             ┆ 1.0209736e7          │
│ y1_d217_VAS_ARN ┆ 333.0         ┆ 255       ┆ 16             ┆ 1.0672886e7          │
│ y1_d217_VAS_ARN ┆ 351.0         ┆ 9         ┆ 2              ┆ 1.1281536e7          │
└─────────────────┴───────────────┴───────────┴────────────────┴──────────────────────┘

# Calculate Hang Time

In [6]:
# Calculate hang time between the two events
hang_times_df = bbip_next_event_df \
                                .join(
                                  bbip_hit_df,
                                  how = "left",
                                  on = ["game_string", "play_per_game"]) \
                                 .with_columns(
                                     hang_time = ((pl.col("next_event_timestamp") - pl.col("hit_timestamp")) / 1000).round(2)\
                                         .over(["game_string", "play_per_game"])
                                 ) \
                                 .filter( # Filter out hits with missing data
                                     pl.col("hang_time") <= 20,
                                     pl.col("hang_time") >= 0,
                                     (pl.col("ball_eventcode").is_in([2, 16]))
                                 ) \
                                .select(["game_string", "play_per_game", "ball_eventcode", "hit_timestamp", "next_event_timestamp", "hang_time", "player_id"]
                                       )

# Calculate Hit Distance

In [24]:
# Add in ball position data to hit and next event timestamp
hit_dist_df = ball_pos_df \
                         .join(
                              hang_times_df,
                              how = "inner",
                              on = ["game_string", "play_per_game"]) \
                         .filter(
                             (pl.col("timestamp") == pl.col("hit_timestamp")) |
                             (pl.col("timestamp") == pl.col("next_event_timestamp"))
                         ) \
                         .with_columns( # calculate the change between the two timestamps
                             change_x = (pl.col("ball_position_x").shift(-1) - pl.col("ball_position_x")).over(["game_string", "play_per_game"]),
                             change_y = (pl.col("ball_position_y").shift(-1) - pl.col("ball_position_y")).over(["game_string", "play_per_game"])
                         ) \
                         .with_columns( # gives us hit distance
                             hit_distance = (pl.col("change_x") ** 2 + pl.col("change_y")** 2).sqrt().over(["game_string", "play_per_game"])
                         ) \
                         .select(
                             ["game_string", "play_per_game", "hang_time", "ball_eventcode", "hit_distance", "change_x", "change_y", "timestamp",
                              "hit_timestamp", "next_event_timestamp", "player_id"]
                         ) \
                         .filter( # filter for balls > 175 to isolate balls hit to the outfield
                             (pl.col("hit_distance") > 175) &
                             (pl.col("hit_distance").is_not_null())
                         ).sort(["game_string", "play_per_game"])

shape: (2_716, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ game_stri ┆ play_per_ ┆ timestamp ┆ ball_posi ┆ … ┆ player_id ┆ change_x  ┆ change_y  ┆ hit_dist │
│ ng        ┆ game      ┆ ---       ┆ tion_x    ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ance     │
│ ---       ┆ ---       ┆ f64       ┆ ---       ┆   ┆ i64       ┆ f64       ┆ f64       ┆ ---      │
│ str       ┆ f64       ┆           ┆ f64       ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ y1_d061_V ┆ 11.0      ┆ 392164.0  ┆ 0.1212141 ┆ … ┆ 255       ┆ 40.799386 ┆ 371.14755 ┆ 373.3833 │
│ KA_PHD    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 07       │
│ y1_d061_V ┆ 22.0      ┆ 717914.0  ┆ 0.0918126 ┆ … ┆ 255       ┆ -179.3391 ┆ 244.07668 ┆ 302.8794 │
│ KA_PHD    ┆           ┆           ┆           ┆   ┆           ┆ 13        ┆ 7         ┆ 25       │
│ y1_d061_V ┆ 28.0      ┆ 973664.0  ┆ -0.514089 ┆ … ┆ 9         ┆ 63.838389 ┆ 186.11079 ┆ 196.7550 │
│ KA_PHD    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 92       │
│ y1_d061_V ┆ 64.0      ┆ 2.016264e ┆ 0.687837  ┆ … ┆ 255       ┆ -3.897357 ┆ 199.36281 ┆ 199.4009 │
│ KA_PHD    ┆           ┆ 6         ┆           ┆   ┆           ┆           ┆ 3         ┆ 04       │
│ y1_d061_V ┆ 88.0      ┆ 2.840064e ┆ 0.2018127 ┆ … ┆ 255       ┆ -110.0516 ┆ 205.65804 ┆ 233.2521 │
│ KA_PHD    ┆           ┆ 6         ┆           ┆   ┆           ┆ 13        ┆           ┆ 96       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ y1_d217_V ┆ 266.0     ┆ 8.565486e ┆ 0.46833   ┆ … ┆ 255       ┆ -90.70953 ┆ 184.88680 ┆ 205.9401 │
│ AS_ARN    ┆           ┆ 6         ┆           ┆   ┆           ┆           ┆ 2         ┆ 57       │
│ y1_d217_V ┆ 290.0     ┆ 9.324686e ┆ -0.238297 ┆ … ┆ 255       ┆ 107.27589 ┆ 366.76256 ┆ 382.1294 │
│ AS_ARN    ┆           ┆ 6         ┆           ┆   ┆           ┆ 7         ┆ 7         ┆ 27       │
│ y1_d217_V ┆ 307.0     ┆ 9.855686e ┆ 0.409482  ┆ … ┆ 255       ┆ -121.5884 ┆ 205.43987 ┆ 238.7243 │
│ AS_ARN    ┆           ┆ 6         ┆           ┆   ┆           ┆ 82        ┆ 1         ┆ 17       │
│ y1_d217_V ┆ 316.0     ┆ 1.0064186 ┆ 0.548085  ┆ … ┆ 9         ┆ 81.629115 ┆ 211.05717 ┆ 226.2928 │
│ AS_ARN    ┆           ┆ e7        ┆           ┆   ┆           ┆           ┆           ┆ 22       │
│ y1_d217_V ┆ 351.0     ┆ 1.1276086 ┆ 0.206844  ┆ … ┆ 9         ┆ 123.51615 ┆ 169.2972  ┆ 209.5657 │
│ AS_ARN    ┆           ┆ e7        ┆           ┆   ┆           ┆ 6         ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Find All Relevant Timestamps

In [19]:
# Add in relevant player pos data 
player_dist_df = player_pos_df\
                            .join(
                                hit_dist_df,
                                how = "inner",
                                on = ["game_string", "play_per_game"]
                            ) \
                            .filter( # all relevant time stamps
                                pl.col("player_id") == of_pos,
                                (pl.col("timestamp") >= pl.col("hit_timestamp")) |
                                (pl.col("timestamp") <= pl.col("next_event_timestamp"))   
                            ) \
                            .select(
                                  ["game_string", "play_per_game", "timestamp", "hit_timestamp", "next_event_timestamp",
                                  "hang_time", "field_x", "field_y", "hit_distance", "ball_eventcode", "player_id"]
                            )

shape: (684_715, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ game_stri ┆ play_per_ ┆ timestamp ┆ hit_times ┆ … ┆ field_y  ┆ hit_dista ┆ ball_even ┆ player_id │
│ ng        ┆ game      ┆ ---       ┆ tamp      ┆   ┆ ---      ┆ nce       ┆ tcode     ┆ ---       │
│ ---       ┆ ---       ┆ f64       ┆ ---       ┆   ┆ f64      ┆ ---       ┆ ---       ┆ i64       │
│ str       ┆ f64       ┆           ┆ f64       ┆   ┆          ┆ f64       ┆ i64       ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ y1_d143_A ┆ 17.0      ┆ 374004.0  ┆ 377454.0  ┆ … ┆ 261.5535 ┆ 229.64456 ┆ 16        ┆ 9         │
│ DQ_ANI    ┆           ┆           ┆           ┆   ┆          ┆ 4         ┆           ┆           │
│ y1_d143_A ┆ 17.0      ┆ 374054.0  ┆ 377454.0  ┆ … ┆ 261.5133 ┆ 229.64456 ┆ 16        ┆ 9         │
│ DQ_ANI    ┆           ┆           ┆           ┆   ┆          ┆ 4         ┆           ┆           │
│ y1_d143_A ┆ 17.0      ┆ 374104.0  ┆ 377454.0  ┆ … ┆ 261.4725 ┆ 229.64456 ┆ 16        ┆ 9         │
│ DQ_ANI    ┆           ┆           ┆           ┆   ┆          ┆ 4         ┆           ┆           │
│ y1_d143_A ┆ 17.0      ┆ 374154.0  ┆ 377454.0  ┆ … ┆ 261.4317 ┆ 229.64456 ┆ 16        ┆ 9         │
│ DQ_ANI    ┆           ┆           ┆           ┆   ┆          ┆ 4         ┆           ┆           │
│ y1_d143_A ┆ 17.0      ┆ 374204.0  ┆ 377454.0  ┆ … ┆ 261.3903 ┆ 229.64456 ┆ 16        ┆ 9         │
│ DQ_ANI    ┆           ┆           ┆           ┆   ┆          ┆ 4         ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ y1_d103_W ┆ 301.0     ┆ 9.870185e ┆ 9.861385e ┆ … ┆ 256.3629 ┆ 287.79281 ┆ 16        ┆ 9         │
│ TH_VAS    ┆           ┆ 6         ┆ 6         ┆   ┆          ┆ 3         ┆           ┆           │
│ y1_d103_W ┆ 301.0     ┆ 9.870235e ┆ 9.861385e ┆ … ┆ 256.2651 ┆ 287.79281 ┆ 16        ┆ 9         │
│ TH_VAS    ┆           ┆ 6         ┆ 6         ┆   ┆          ┆ 3         ┆           ┆           │
│ y1_d103_W ┆ 301.0     ┆ 9.870285e ┆ 9.861385e ┆ … ┆ 256.1682 ┆ 287.79281 ┆ 16        ┆ 9         │
│ TH_VAS    ┆           ┆ 6         ┆ 6         ┆   ┆          ┆ 3         ┆           ┆           │
│ y1_d103_W ┆ 301.0     ┆ 9.870335e ┆ 9.861385e ┆ … ┆ 256.0707 ┆ 287.79281 ┆ 16        ┆ 9         │
│ TH_VAS    ┆           ┆ 6         ┆ 6         ┆   ┆          ┆ 3         ┆           ┆           │
│ y1_d103_W ┆ 301.0     ┆ 9.870385e ┆ 9.861385e ┆ … ┆ 255.9729 ┆ 287.79281 ┆ 16        ┆ 9         │
│ TH_VAS    ┆           ┆ 6         ┆ 6         ┆   ┆          ┆ 3         ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

# Join with Ball Pos Data

In [20]:
# Add in relevant ball pos data 
player_ball_df = player_dist_df \
                                .join(
                                    ball_pos_df,
                                    how = "inner",
                                    on = ["game_string", "play_per_game", "timestamp"]
                                ) \
                                .select(
                                      ["game_string", "play_per_game", "timestamp", "hit_timestamp", "next_event_timestamp", "ball_eventcode", "player_id",
                                      "hang_time", "field_x", "field_y", "hit_distance", "ball_position_x", "ball_position_y", "ball_position_z"]
                                )

shape: (402_891, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ game_stri ┆ play_per_ ┆ timestamp ┆ hit_times ┆ … ┆ hit_dista ┆ ball_posi ┆ ball_posi ┆ ball_pos │
│ ng        ┆ game      ┆ ---       ┆ tamp      ┆   ┆ nce       ┆ tion_x    ┆ tion_y    ┆ ition_z  │
│ ---       ┆ ---       ┆ f64       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ f64       ┆           ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ y1_d143_A ┆ 17.0      ┆ 377004.0  ┆ 377454.0  ┆ … ┆ 229.64456 ┆ -1.611609 ┆ 54.177    ┆ 6.31017  │
│ DQ_ANI    ┆           ┆           ┆           ┆   ┆ 4         ┆           ┆           ┆          │
│ y1_d143_A ┆ 17.0      ┆ 377054.0  ┆ 377454.0  ┆ … ┆ 229.64456 ┆ -1.479819 ┆ 48.1371   ┆ 6.16053  │
│ DQ_ANI    ┆           ┆           ┆           ┆   ┆ 4         ┆           ┆           ┆          │
│ y1_d143_A ┆ 17.0      ┆ 377104.0  ┆ 377454.0  ┆ … ┆ 229.64456 ┆ -1.324644 ┆ 42.1458   ┆ 5.92881  │
│ DQ_ANI    ┆           ┆           ┆           ┆   ┆ 4         ┆           ┆           ┆          │
│ y1_d143_A ┆ 17.0      ┆ 377154.0  ┆ 377454.0  ┆ … ┆ 229.64456 ┆ -1.146081 ┆ 36.2028   ┆ 5.61504  │
│ DQ_ANI    ┆           ┆           ┆           ┆   ┆ 4         ┆           ┆           ┆          │
│ y1_d143_A ┆ 17.0      ┆ 377204.0  ┆ 377454.0  ┆ … ┆ 229.64456 ┆ -0.94413  ┆ 30.3081   ┆ 5.21919  │
│ DQ_ANI    ┆           ┆           ┆           ┆   ┆ 4         ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ y1_d103_W ┆ 301.0     ┆ 9.869485e ┆ 9.861385e ┆ … ┆ 287.79281 ┆ 106.1277  ┆ 137.8665  ┆ -0.4962  │
│ TH_VAS    ┆           ┆ 6         ┆ 6         ┆   ┆ 3         ┆           ┆           ┆          │
│ y1_d103_W ┆ 301.0     ┆ 9.869535e ┆ 9.861385e ┆ … ┆ 287.79281 ┆ 104.3982  ┆ 135.3654  ┆ -0.37215 │
│ TH_VAS    ┆           ┆ 6         ┆ 6         ┆   ┆ 3         ┆           ┆           ┆          │
│ y1_d103_W ┆ 301.0     ┆ 9.869585e ┆ 9.861385e ┆ … ┆ 287.79281 ┆ 102.6687  ┆ 132.8643  ┆ -0.2481  │
│ TH_VAS    ┆           ┆ 6         ┆ 6         ┆   ┆ 3         ┆           ┆           ┆          │
│ y1_d103_W ┆ 301.0     ┆ 9.869635e ┆ 9.861385e ┆ … ┆ 287.79281 ┆ 100.9392  ┆ 130.3635  ┆ -0.12405 │
│ TH_VAS    ┆           ┆ 6         ┆ 6         ┆   ┆ 3         ┆           ┆           ┆          │
│ y1_d103_W ┆ 301.0     ┆ 9.869685e ┆ 9.861385e ┆ … ┆ 287.79281 ┆ 99.2097   ┆ 127.8624  ┆ 0.0      │
│ TH_VAS    ┆           ┆ 6         ┆ 6         ┆   ┆ 3         ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Find Angle of Descent

In [26]:
# grab the tail of the relevant time stamps
ball_pos_last_20 = player_ball_df \
                                .sort(
                                    ["game_string", "play_per_game", "timestamp"]
                                ) \
                                .group_by(
                                    ["game_string", "play_per_game"]
                                ) \
                                .tail(20)
# calc angle of descent
descent_by_play = ball_pos_last_20 \
                              .with_columns( # calc change in x, y, z during the tail.
                                  change_x = (pl.col("ball_position_x").max() - pl.col("ball_position_x").min()).over(["game_string", "play_per_game"]),
                                  change_y = (pl.col("ball_position_y").max() - pl.col("ball_position_y").min()).over(["game_string", "play_per_game"]),
                                  change_z = (pl.col("ball_position_z").min() - pl.col("ball_position_z").max()).over(["game_string", "play_per_game"]),
                                  ) \
                              .with_columns( # ground distance covered
                                  ground_distance = (pl.col("change_x") ** 2 + pl.col("change_y") ** 2).sqrt()
                              ) \
                              .with_columns( # drop over ground distance
                                  descent_angle_deg = pl.arctan2("change_z", "ground_distance").degrees()
                              ) \
                              .select(
                                  ["game_string", "play_per_game", "hang_time", "hit_distance", "descent_angle_deg", "ball_eventcode"]
                              ) \
                              .unique( # once per play
                              )

shape: (53_840, 6)
┌─────────────────┬───────────────┬───────────┬──────────────┬───────────────────┬────────────────┐
│ game_string     ┆ play_per_game ┆ hang_time ┆ hit_distance ┆ descent_angle_deg ┆ ball_eventcode │
│ ---             ┆ ---           ┆ ---       ┆ ---          ┆ ---               ┆ ---            │
│ str             ┆ f64           ┆ f64       ┆ f64          ┆ f64               ┆ i64            │
╞═════════════════╪═══════════════╪═══════════╪══════════════╪═══════════════════╪════════════════╡
│ y1_d139_VAS_ARN ┆ 130.0         ┆ 2.35      ┆ 273.836537   ┆ -13.768121        ┆ 16             │
│ y1_d139_VAS_ARN ┆ 130.0         ┆ 2.35      ┆ 273.836537   ┆ -13.768121        ┆ 16             │
│ y1_d139_VAS_ARN ┆ 130.0         ┆ 2.35      ┆ 273.836537   ┆ -13.768121        ┆ 16             │
│ y1_d139_VAS_ARN ┆ 130.0         ┆ 2.35      ┆ 273.836537   ┆ -13.768121        ┆ 16             │
│ y1_d139_VAS_ARN ┆ 130.0         ┆ 2.35      ┆ 273.836537   ┆ -13.768121        ┆ 16             │
│ …               ┆ …             ┆ …         ┆ …            ┆ …                 ┆ …              │
│ y1_d106_OER_ANI ┆ 218.0         ┆ 2.28      ┆ 217.52153    ┆ -12.688195        ┆ 16             │
│ y1_d106_OER_ANI ┆ 218.0         ┆ 2.28      ┆ 217.52153    ┆ -12.688195        ┆ 16             │
│ y1_d106_OER_ANI ┆ 218.0         ┆ 2.28      ┆ 217.52153    ┆ -12.688195        ┆ 16             │
│ y1_d106_OER_ANI ┆ 218.0         ┆ 2.28      ┆ 217.52153    ┆ -12.688195        ┆ 16             │
│ y1_d106_OER_ANI ┆ 218.0         ┆ 2.28      ┆ 217.52153    ┆ -12.688195        ┆ 16             │
└─────────────────┴───────────────┴───────────┴──────────────┴───────────────────┴────────────────┘

# Find Optimal Route Distance and Attack Angle

In [31]:
# Isolate OFer position at contact
starting_pos_df = player_ball_df \
                            .filter(
                                pl.col("timestamp") == pl.col("hit_timestamp"),
                            ) \
                            .select(
                                ["game_string", "play_per_game", "timestamp", "field_x", "field_y", "ball_eventcode", "hit_timestamp", "player_id"]
                            )
# Isolate ball position at next event
ball_pos_next_df = player_ball_df \
                            .filter(
                                pl.col("timestamp") == pl.col("next_event_timestamp").over(["game_string", "play_per_game"]),
                            ) \
                            .select(
                                ["game_string", "play_per_game", "hang_time", "ball_position_x", "ball_position_y", "next_event_timestamp"]
                            )
# Join and calculate ORD and Atk Angle
ord_atk_df = starting_pos_df \
                            .join(
                                 ball_pos_next_df,
                                 how = "inner",
                                 on = ["game_string", "play_per_game"] 
                                ) \
                            .with_columns( # Change between timestamps
                                change_x = pl.col("field_x") - pl.col("ball_position_x"),
                                change_y = pl.col("field_y") - pl.col("ball_position_y"),
                            ) \
                            .with_columns( # Angle from fielder position to ball ending position
                                attack_angle_deg = (pl.arctan2(((pl.col("field_y")) - (pl.col("ball_position_y"))),
                                ((pl.col("field_x")) - (pl.col("ball_position_x")))).degrees()) \
                                .over(["game_string", "play_per_game"]),
                                # Distance formula for player distance to ball end point
                                optimal_route_distance = ((pl.col("change_x") ** 2) + (pl.col("change_y") ** 2)).sqrt() \
                                .over(["game_string", "play_per_game"])
                            ) \
                            .select(
                                ["game_string", "play_per_game", "optimal_route_distance", "attack_angle_deg"]
                            ) \
                            .sort(
                                ["game_string", "play_per_game"]
                                )

# Join ORD and Attack Angle with Descent

In [33]:
# Combine into full data frame, add catch status, and shrink to unique plays
full_df = descent_by_play \
                        .join(
                            ord_atk_df,
                            how = "left",
                            on = ["game_string", "play_per_game"]
                        ) \
                        .with_columns( # catch status
                            catch_status =  
                                pl.when(pl.col("ball_eventcode") == 2)
                                .then(1)
                                .otherwise(0)
                        ) \
                        .sort(["game_string", "play_per_game"]) \
                        .unique(
                            subset= ["game_string", "play_per_game"],
                            keep="first"
                        ) \
                        .drop_nulls(
                        )

shape: (2_674, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ game_stri ┆ play_per_ ┆ hang_time ┆ hit_dista ┆ … ┆ ball_even ┆ optimal_r ┆ attack_an ┆ catch_st │
│ ng        ┆ game      ┆ ---       ┆ nce       ┆   ┆ tcode     ┆ oute_dist ┆ gle_deg   ┆ atus     │
│ ---       ┆ ---       ┆ f64       ┆ ---       ┆   ┆ ---       ┆ ance      ┆ ---       ┆ ---      │
│ str       ┆ f64       ┆           ┆ f64       ┆   ┆ i64       ┆ ---       ┆ f64       ┆ i32      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ y1_d171_I ┆ 107.0     ┆ 5.2       ┆ 319.39978 ┆ … ┆ 2         ┆ 20.331688 ┆ -124.8076 ┆ 1        │
│ GL_ANI    ┆           ┆           ┆           ┆   ┆           ┆           ┆ 52        ┆          │
│ y1_d126_M ┆ 188.0     ┆ 3.1       ┆ 252.11272 ┆ … ┆ 16        ┆ 217.34982 ┆ 14.914112 ┆ 0        │
│ EX_ANI    ┆           ┆           ┆ 6         ┆   ┆           ┆ 5         ┆           ┆          │
│ y1_d169_M ┆ 70.0      ┆ 3.83      ┆ 341.95507 ┆ … ┆ 16        ┆ 82.899802 ┆ -66.0605  ┆ 0        │
│ PC_PHD    ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ y1_d074.5 ┆ 186.0     ┆ 4.15      ┆ 213.88859 ┆ … ┆ 16        ┆ 292.43406 ┆ 20.82061  ┆ 0        │
│ _AIP_ARN  ┆           ┆           ┆ 9         ┆   ┆           ┆ 4         ┆           ┆          │
│ y1_d190_P ┆ 140.0     ┆ 2.71      ┆ 240.32247 ┆ … ┆ 16        ┆ 93.996782 ┆ 107.11961 ┆ 0        │
│ HD_ARN    ┆           ┆           ┆           ┆   ┆           ┆           ┆ 5         ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ y1_d209_Q ┆ 290.0     ┆ 4.3       ┆ 240.73278 ┆ … ┆ 16        ┆ 168.96083 ┆ 7.646273  ┆ 0        │
│ HX_ANI    ┆           ┆           ┆ 6         ┆   ┆           ┆ 1         ┆           ┆          │
│ y1_d077_P ┆ 179.0     ┆ 2.2       ┆ 198.96957 ┆ … ┆ 16        ┆ 84.452491 ┆ 55.673452 ┆ 0        │
│ HD_VAS    ┆           ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ y1_d207_A ┆ 88.0      ┆ 3.0       ┆ 261.42613 ┆ … ┆ 16        ┆ 273.65305 ┆ 8.967193  ┆ 0        │
│ TL_PHD    ┆           ┆           ┆ 4         ┆   ┆           ┆ 6         ┆           ┆          │
│ y1_d172_I ┆ 288.0     ┆ 2.5       ┆ 228.81781 ┆ … ┆ 16        ┆ 66.021877 ┆ 31.264026 ┆ 0        │
│ GL_ANI    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ y1_d152_V ┆ 64.0      ┆ 3.55      ┆ 343.86615 ┆ … ┆ 16        ┆ 106.17299 ┆ -46.81200 ┆ 0        │
│ AS_PHD    ┆           ┆           ┆ 5         ┆   ┆           ┆           ┆ 1         ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Train/Test Split

In [14]:
# Set seed
np.random.seed(27) # My lucky number :)

# Convert df to numpy
np_df = full_df[["optimal_route_distance", "hang_time", "descent_angle_deg", "attack_angle_deg", "catch_status"]].to_numpy()

# Specify X and Y
x = np_df[:, [0, 1, 2, 3]]
y = np_df[:, 4]

# Split data into training and testing, 70/30
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size = 0.3
)

# Logistic Regression

In [35]:
# Logistic Regression Model
logistic_regression_model = LogisticRegression().fit(x_train, y_train)

# # Look Inside the Model
# logistic_regression_model

LogisticRegression()

# Create Table for Metrics

In [16]:
# catch_prob_training_results = pl.DataFrame({
#     "actual" : y_train,
#     "logistic_reg_class" : logistic_regression_model.predict(x_train),
#     "logistic_reg_prob" : logistic_regression_model.predict_proba(x_train)
# })
# catch_prob_testing_results = pl.DataFrame({
#     "actual" : y_test,
#     "logistic_reg_class" : logistic_regression_model.predict(x_test),
#     "logistic_reg_prob" : logistic_regression_model.predict_proba(x_test),
# })

# # Combine into 1 data frame
# full_catch_prob_results = pl.concat(
#     [catch_prob_training_results, catch_prob_testing_results],
#     how = "vertical"
# )

# full_catch_prob_results

# Model Evaluation - Confusion Matrix

In [17]:
# # Confusion Matrix for Logistic Regression Model
# logistic_regression_cm = sklearn.metrics.confusion_matrix(full_catch_prob_results["actual"], full_catch_prob_results["logistic_reg_class"])

# logistic_regression_cm

# Model Evaluation Metrics

In [18]:
# accuracy = sklearn.metrics.accuracy_score(full_catch_prob_results["actual"], full_catch_prob_results["logistic_reg_class"])

# precision = sklearn.metrics.precision_score(full_catch_prob_results["actual"], full_catch_prob_results["logistic_reg_class"])

# recall = sklearn.metrics.recall_score(full_catch_prob_results["actual"], full_catch_prob_results["logistic_reg_class"])

# rmse = sklearn.metrics.root_mean_squared_error(full_catch_prob_results["actual"], full_catch_prob_results["logistic_reg_class"])

# print(f'Accuracy {accuracy:.2f},\nPrecision {precision:.2f},\nRecall {recall:.2f},\nRMSE {rmse:.2f}')